title = "Arnaud Jeglot"
baseURL = ""
languageCode = "en-us"
theme = ["ananke"]
# publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

#[sitemap]
 # changefreq = "monthly"
  #priority = 0.5
  #filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/AJeglot"
  instagram = ""
  youtube = ""
  github = ""
  email= "ajeglot@gmail.com"
  linkedin = "https://www.linkedin.com/in/ajeglot/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-green"
  featured_image = 'images/background.jpeg'
  recent_posts_number = 5
  body_classes = "avenir bg-near-white"